<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-TRTRPCDI" name="TestngSample.Actitime_ExceptionAndTimeout" tests="2" failures="0" timestamp="19 Sep 2022 13:40:34 GMT" time="1.021" errors="1">
  <testcase name="dividedByZeroExample1" time="0.008" classname="TestngSample.Actitime_ExceptionAndTimeout"/>
  <testcase name="executetimeOut" time="1.013" classname="TestngSample.Actitime_ExceptionAndTimeout">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method TestngSample.Actitime_ExceptionAndTimeout.executetimeOut() didn&#039;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestngSample.Actitime_ExceptionAndTimeout.executetimeOut() didn't finish within the time-out 1000
]]>
    </error>
  </testcase> <!-- executetimeOut -->
</testsuite> <!-- TestngSample.Actitime_ExceptionAndTimeout -->
